[project]
name = "cloud-keep-alive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=1.3.1",
    "lxml>=6.0.2",
    "requests>=2.32.5",
]
